### ISSUE TITLE
图片似乎发不出来

### ISSUE THREAD

**Issue by a1232580** [KafCoppelia/nonebot_plugin_fortune#100]
图片已经生成了，在./data/fortune/out 下找到了这张图片，但是机器人没有发出来  用的shamrock 
`2643104832, id = 1993716907|81429, msg = 今日运势)[14:27:51] ERROR java.io.FileNotFoundException: root/df/data/fortune/out/463925324_2643104832.png: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7719)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 7 more
[14:27:51] INFO 预发送消息(1702432709 | 81429 | 7310477883680838146)[14:27:51] INFO Update message info from 81429 to 81430[14:27:51] INFO 消息发送: 463925324, code: 0

**Comment by aknyzsd** [comment]
我也遇到了类似问题，不过运行环境有些不同，我是在win下部署的nb端，用模拟器跑的shamrock，使用filehost插件实现的路径链接，有文本生成但不能发出图片（别的插件可以）
