### ISSUE TITLE
怪

### ISSUE THREAD

**Issue by Death-Star-Glory** [KafCoppelia/nonebot_plugin_fortune#93]
09-03 15:47:17 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_fortune) failed.
Traceback (most recent call last):
  File "D:\zm\DDBOT\AIAS\bot.py", line 17, in <module>
    nonebot.run()
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot_plugin_fortune\__init__.py", line 158, in _
    await change_theme.finish("已设置当前群抽签主题~")
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 483, in finish
    await cls.send(message, **kwargs)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 467, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot_plugin_guild_patch\__init__.py", line 30, in patched_send
    return await original_send(self, event, message, **kwargs)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 221, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 143, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "D:\zm\DDBOT\AIAS\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='1', message='send group message failed: blocked by server', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='send group message failed: blocked by server')

**Comment by Death-Star-Glory** [comment]
风控了，没事了
